spring:
  datasource:
    url: jdbc:mysql://localhost:3306/merry_db
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true