package jp.co.hjn.merryapi.infrastructure.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.hjn.merryapi.infrastructure.model.DayOff;
import jp.co.hjn.merryapi.infrastructure.model.DayOffExample;

@Mapper
public interface DayOffMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    long countByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int deleteByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int insert(DayOff row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int insertSelective(DayOff row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    List<DayOff> selectByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    DayOff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByExampleSelective(@Param("row") DayOff row, @Param("example") DayOffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByExample(@Param("row") DayOff row, @Param("example") DayOffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByPrimaryKeySelective(DayOff row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByPrimaryKey(DayOff row);
}