package jp.co.hjn.merryapi.infrastructure.model;

import java.util.Date;

public class DayOff {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.id
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.employee_id
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Integer employeeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.name_first
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Date startDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.name_first
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Date endDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.created_at
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.updated_at
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Date updatedAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.deleted_at
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.id
     *
     * @return the value of employee.id
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.id
     *
     * @param id the value for employee.id
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.employee_id
     *
     * @return the value of employee.employee_id
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.employee_id
     *
     * @param id the value for employee.employee_id
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.startDate
     *
     * @return the value of employee.startDate
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.startDate
     *
     * @param birthday the value for employee.startDate
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.endDate
     *
     * @return the value of employee.endDate
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.endDate
     *
     * @param birthday the value for employee.endDate
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.created_at
     *
     * @return the value of employee.created_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.created_at
     *
     * @param createdAt the value for employee.created_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.updated_at
     *
     * @return the value of employee.updated_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.updated_at
     *
     * @param updatedAt the value for employee.updated_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.deleted_at
     *
     * @return the value of employee.deleted_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.deleted_at
     *
     * @param deletedAt the value for employee.deleted_at
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}